package com.renacerfinancierousa.mirenacer;

import android.app.Activity;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.text.InputType;
import android.view.Gravity;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ProgressBar;
import android.widget.ScrollView;
import android.widget.TextView;
import org.json.JSONArray;
import org.json.JSONObject;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

public class MainActivity extends Activity {
    private final ApiClient api=new ApiClient(); private SecureSession session; private String token=""; private LinearLayout content,nav;
    private final int navy=Color.rgb(5,35,72),blue=Color.rgb(23,100,216),ink=Color.rgb(32,54,80),muted=Color.rgb(113,129,151),surface=Color.rgb(244,247,250),teal=Color.rgb(23,169,154);
    @Override public void onCreate(Bundle b){super.onCreate(b);session=new SecureSession(this);token=session.load();if(token.isEmpty())showLogin();else showApp();}

    private void showLogin(){
        ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setBackgroundColor(navy);LinearLayout box=column();box.setGravity(Gravity.CENTER);box.setPadding(dp(28),dp(50),dp(28),dp(36));scroll.addView(box);
        ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.renacer_icon);logo.setScaleType(ImageView.ScaleType.CENTER_CROP);box.addView(logo,new LinearLayout.LayoutParams(dp(86),dp(86)));box.addView(space(18));box.addView(center("RENACER FINANCIERO USA",12,Color.rgb(164,198,229),true));box.addView(center("Bienvenido a Mi Renacer",28,Color.WHITE,true));box.addView(center("Consulta tu progreso, auditorías y documentos desde tu aplicación privada.",15,Color.rgb(220,233,246),false));box.addView(space(26));
        LinearLayout card=column();card.setPadding(dp(20),dp(22),dp(20),dp(22));card.setBackground(bg(Color.WHITE,Color.WHITE,18,0));box.addView(card,new LinearLayout.LayoutParams(-1,-2));card.addView(text("Acceso seguro",19,ink,true));card.addView(text("Ingresa con la cuenta asociada a tu expediente.",13,muted,false));card.addView(space(12));
        EditText user=input("Usuario o correo electrónico",false),pass=input("Contraseña",true);card.addView(user);card.addView(space(8));card.addView(pass);card.addView(space(14));Button login=button("Ingresar a Mi Renacer",blue);card.addView(login,new LinearLayout.LayoutParams(-1,dp(50)));TextView error=text("",13,Color.rgb(180,45,45),true);error.setPadding(0,dp(10),0,0);card.addView(error);
        login.setOnClickListener(v->{if(user.getText().toString().trim().isEmpty()||pass.getText().toString().isEmpty()){error.setText("Ingresa tu usuario y contraseña.");return;}login.setEnabled(false);login.setText("Conectando…");api.login(user.getText().toString().trim(),pass.getText().toString(),(json,err,status)->runOnUiThread(()->{login.setEnabled(true);login.setText("Ingresar a Mi Renacer");if(err!=null){error.setText(err);return;}try{token=json.getJSONObject("data").getString("access_token");session.save(token);pass.setText("");showApp();}catch(Exception e){error.setText("La respuesta del servidor no es válida.");}}));});setContentView(scroll);
    }

    private void showApp(){
        LinearLayout root=column();root.setBackgroundColor(surface);LinearLayout header=new LinearLayout(this);header.setGravity(Gravity.CENTER_VERTICAL);header.setPadding(dp(16),dp(11),dp(16),dp(11));header.setBackgroundColor(navy);ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.renacer_icon);logo.setScaleType(ImageView.ScaleType.CENTER_CROP);header.addView(logo,new LinearLayout.LayoutParams(dp(42),dp(42)));LinearLayout brand=column();brand.setPadding(dp(10),0,0,0);brand.addView(text("Mi Renacer",20,Color.WHITE,true));brand.addView(text("PORTAL FINANCIERO",9,Color.rgb(167,197,226),true));header.addView(brand,new LinearLayout.LayoutParams(0,-2,1));header.addView(text("● PRIVADO",10,Color.rgb(104,225,190),true));root.addView(header,new LinearLayout.LayoutParams(-1,dp(66)));
        ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);content=column();content.setPadding(dp(16),dp(18),dp(16),dp(28));scroll.addView(content);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));nav=new LinearLayout(this);nav.setGravity(Gravity.CENTER);nav.setPadding(dp(5),dp(5),dp(5),dp(7));nav.setBackgroundColor(Color.WHITE);addNav("⌂","Inicio","dashboard");addNav("↗","Crédito","scores");addNav("▣","Auditar","audits");addNav("▤","Archivos","documents");addNav("●","Perfil","me");root.addView(nav,new LinearLayout.LayoutParams(-1,dp(72)));setContentView(root);loadSection("dashboard");
    }

    private void addNav(String icon,String label,String endpoint){LinearLayout item=column();item.setGravity(Gravity.CENTER);item.setPadding(dp(2),dp(5),dp(2),dp(4));item.addView(center(icon,18,muted,true));item.addView(center(label,9,muted,true));item.setTag(endpoint);item.setOnClickListener(v->loadSection(endpoint));nav.addView(item,new LinearLayout.LayoutParams(0,-1,1));}
    private void activeNav(String endpoint){for(int n=0;n<nav.getChildCount();n++){LinearLayout item=(LinearLayout)nav.getChildAt(n);boolean active=endpoint.equals(item.getTag());item.setBackground(active?bg(Color.rgb(235,243,255),Color.rgb(235,243,255),12,0):null);for(int j=0;j<item.getChildCount();j++)((TextView)item.getChildAt(j)).setTextColor(active?blue:muted);}}
    private void loadSection(String endpoint){activeNav(endpoint);content.removeAllViews();LinearLayout loading=column();loading.setGravity(Gravity.CENTER);loading.setPadding(0,dp(80),0,0);loading.addView(new ProgressBar(this));loading.addView(center("Cargando tu información…",13,muted,false));content.addView(loading);api.get(endpoint,token,(json,err,status)->runOnUiThread(()->{content.removeAllViews();if(status==401){session.clear();token="";showLogin();return;}if(err!=null){content.addView(empty("No pudimos cargar esta sección",err));return;}JSONObject data=json.optJSONObject("data");if(data==null){content.addView(empty("Sin información","No hay datos disponibles."));return;}if(endpoint.equals("dashboard"))dashboard(data);else if(endpoint.equals("scores"))scores(data);else if(endpoint.equals("audits"))audits(data);else if(endpoint.equals("documents"))documents(data);else profile(data);}));}

    private void dashboard(JSONObject d){
        content.addView(text("Hola, "+firstName(d.optString("client_name","Cliente")),27,ink,true));content.addView(text("Aquí tienes el resumen de tu progreso financiero.",14,muted,false));content.addView(space(15));JSONObject s=d.optJSONObject("scores");if(s!=null){content.addView(section("Tus scores actuales","Última información registrada"));LinearLayout row=new LinearLayout(this);JSONObject ch=s.optJSONObject("change");row.addView(scoreCard("EXPERIAN",s.optInt("experian"),ch==null?0:ch.optInt("experian"),Color.rgb(92,73,174)),weight());row.addView(scoreCard("EQUIFAX",s.optInt("equifax"),ch==null?0:ch.optInt("equifax"),Color.rgb(184,55,61)),weight());row.addView(scoreCard("TRANSUNION",s.optInt("transunion"),ch==null?0:ch.optInt("transunion"),Color.rgb(38,111,181)),weight());content.addView(row);content.addView(space(12));}
        JSONObject j=d.optJSONObject("journey");if(j!=null){LinearLayout c=card();LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.addView(text("Credit Journey",18,ink,true),new LinearLayout.LayoutParams(0,-2,1));top.addView(pill(j.optInt("progress")+"%",teal));c.addView(top);c.addView(text(stage(j.optString("stage")),13,muted,false));ProgressBar p=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);p.setMax(100);p.setProgress(j.optInt("progress"));p.setProgressTintList(android.content.res.ColorStateList.valueOf(teal));LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-1,dp(8));pp.setMargins(0,dp(12),0,dp(9));c.addView(p,pp);c.addView(text("Próxima revisión: "+date(j.optString("next_review")),12,muted,false));content.addView(c);}
        JSONObject c=d.optJSONObject("counts");if(c!=null){content.addView(section("Tu expediente","Información disponible en RAE"));LinearLayout row=new LinearLayout(this);row.addView(metric("▣",c.optInt("audits"),"Auditorías"),weight());row.addView(metric("▤",c.optInt("documents"),"Documentos"),weight());row.addView(metric("◎",c.optInt("active_goals"),"Objetivos"),weight());content.addView(row);}
    }
    private void scores(JSONObject d){content.addView(section("Historial de crédito","Evolución registrada de los tres burós"));JSONArray a=d.optJSONArray("items");if(a==null||a.length()==0){content.addView(empty("Sin scores","Todavía no hay registros."));return;}for(int i=a.length()-1;i>=0;i--){JSONObject x=a.optJSONObject(i);LinearLayout c=card();c.addView(text(date(x.optString("date")),14,ink,true));LinearLayout row=new LinearLayout(this);row.addView(mini("Experian",x.optInt("experian"),Color.rgb(92,73,174)),weight());row.addView(mini("Equifax",x.optInt("equifax"),Color.rgb(184,55,61)),weight());row.addView(mini("TransUnion",x.optInt("transunion"),Color.rgb(38,111,181)),weight());c.addView(row);content.addView(c);}}
    private void audits(JSONObject d){content.addView(section("Mis auditorías","Toca una auditoría para ver sus hallazgos"));JSONArray a=d.optJSONArray("items");if(a==null||a.length()==0){content.addView(empty("Sin auditorías","No hay auditorías compartidas."));return;}for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);LinearLayout c=card();LinearLayout top=new LinearLayout(this);top.addView(text("Auditoría #"+x.optInt("id"),17,ink,true),new LinearLayout.LayoutParams(0,-2,1));top.addView(pill(status(x.optString("status")),teal));c.addView(top);c.addView(text("Burós: "+bureaus(x.optJSONArray("bureaus")),13,muted,false));c.addView(text("Fecha: "+date(x.optString("completed_at",x.optString("created_at"))),12,muted,false));int id=x.optInt("id");c.setOnClickListener(v->auditDetail(id));content.addView(c);}}
    private void auditDetail(int id){content.removeAllViews();content.addView(center("Cargando auditoría…",14,muted,false));api.get("audits/"+id,token,(json,err,statusCode)->runOnUiThread(()->{content.removeAllViews();if(err!=null){content.addView(empty("No se pudo abrir",err));return;}TextView back=text("‹  Volver a auditorías",14,blue,true);back.setPadding(0,0,0,dp(12));back.setOnClickListener(v->loadSection("audits"));content.addView(back);content.addView(section("Auditoría #"+id,"Hallazgos educativos del expediente"));JSONObject d=json.optJSONObject("data");JSONArray a=d==null?null:d.optJSONArray("findings");if(a==null||a.length()==0){content.addView(empty("Sin hallazgos","No se registraron hallazgos estructurados."));return;}for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);LinearLayout c=card();c.addView(pill(priority(x.optString("priority")),priorityColor(x.optString("priority"))));c.addView(text(x.optString("issue_type","Observación"),16,ink,true));c.addView(text(x.optString("creditor"),12,muted,true));c.addView(text(x.optString("summary"),13,muted,false));c.addView(text("Revisión sugerida",11,blue,true));c.addView(text(x.optString("suggested_review"),13,ink,false));content.addView(c);}}));}
    private void documents(JSONObject d){content.addView(section("Mis documentos","Archivos autorizados para tu aplicación"));JSONArray a=d.optJSONArray("items");if(a==null||a.length()==0){content.addView(empty("Sin documentos","No hay documentos compartidos."));return;}for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);LinearLayout c=card();LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);TextView icon=center(fileIcon(x.optString("mime_type")),10,Color.WHITE,true);icon.setBackground(bg(navy,navy,10,0));row.addView(icon,new LinearLayout.LayoutParams(dp(48),dp(48)));LinearLayout info=column();info.setPadding(dp(12),0,0,0);info.addView(text(x.optString("description",x.optString("name")),15,ink,true));info.addView(text(x.optString("category")+" · "+fileSize(x.optLong("size_bytes")),11,muted,false));row.addView(info,new LinearLayout.LayoutParams(0,-2,1));row.addView(text("›",26,blue,true));c.addView(row);content.addView(c);}}
    private void profile(JSONObject d){content.addView(section("Mi perfil","Información vinculada con tu expediente"));LinearLayout c=card();c.addView(text(d.optString("display_name"),19,ink,true));c.addView(text(d.optString("email"),13,muted,false));c.addView(text(d.optString("phone"),13,muted,false));content.addView(c);JSONObject a=d.optJSONObject("address");if(a!=null){LinearLayout ad=card();ad.addView(text("Dirección",15,ink,true));ad.addView(text(a.optString("line1")+"\n"+a.optString("city")+", "+a.optString("state")+" "+a.optString("zip"),13,muted,false));content.addView(ad);}content.addView(text("🔒 Tu sesión está protegida y el token se almacena cifrado en el teléfono.",12,muted,false));content.addView(space(12));Button out=button("Cerrar sesión",navy);content.addView(out,new LinearLayout.LayoutParams(-1,dp(50)));out.setOnClickListener(v->api.logout(token,(j,e,s)->runOnUiThread(()->{session.clear();token="";showLogin();})));}

    private LinearLayout card(){LinearLayout c=column();c.setPadding(dp(16),dp(15),dp(16),dp(15));c.setBackground(bg(Color.WHITE,Color.rgb(224,231,238),16,1));c.setElevation(dp(2));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(11);c.setLayoutParams(p);return c;}
    private LinearLayout empty(String title,String body){LinearLayout c=card();c.setGravity(Gravity.CENTER);c.setPadding(dp(22),dp(32),dp(22),dp(32));c.addView(center(title,17,ink,true));c.addView(center(body,13,muted,false));return c;}
    private LinearLayout scoreCard(String label,int value,int change,int color){LinearLayout c=column();c.setGravity(Gravity.CENTER);c.setPadding(dp(3),dp(13),dp(3),dp(13));c.setBackground(bg(Color.WHITE,Color.rgb(225,232,239),14,1));c.addView(center(label,8,color,true));c.addView(center(value>0?String.valueOf(value):"—",27,ink,true));String delta=change>0?"↑ +"+change:change<0?"↓ "+change:"Sin cambio";c.addView(center(delta,9,change>0?teal:change<0?Color.rgb(190,65,65):muted,true));return c;}
    private LinearLayout mini(String label,int value,int color){LinearLayout c=column();c.setGravity(Gravity.CENTER);c.setPadding(dp(2),dp(10),dp(2),0);c.addView(center(label,9,color,true));c.addView(center(value>0?String.valueOf(value):"—",20,ink,true));return c;}
    private LinearLayout metric(String icon,int value,String label){LinearLayout c=column();c.setGravity(Gravity.CENTER);c.setPadding(dp(2),dp(13),dp(2),dp(13));c.setBackground(bg(Color.WHITE,Color.rgb(225,232,239),14,1));c.addView(center(icon,17,blue,true));c.addView(center(String.valueOf(value),22,ink,true));c.addView(center(label,9,muted,true));return c;}
    private LinearLayout section(String title,String subtitle){LinearLayout c=column();c.setPadding(0,dp(8),0,dp(9));c.addView(text(title,20,ink,true));c.addView(text(subtitle,12,muted,false));return c;}
    private TextView pill(String label,int color){TextView p=center(label,9,color,true);p.setPadding(dp(9),dp(5),dp(9),dp(5));p.setBackground(bg(Color.argb(25,Color.red(color),Color.green(color),Color.blue(color)),Color.TRANSPARENT,20,0));return p;}
    private EditText input(String hint,boolean password){EditText e=new EditText(this);e.setHint(hint);e.setTextSize(15);e.setSingleLine(true);e.setPadding(dp(13),dp(10),dp(13),dp(10));e.setBackground(bg(Color.rgb(247,249,251),Color.rgb(215,224,233),10,1));if(password)e.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);return e;}
    private Button button(String label,int color){Button b=new Button(this);b.setText(label);b.setAllCaps(false);b.setTextSize(14);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setBackground(bg(color,color,12,0));b.setTextColor(Color.WHITE);return b;}
    private TextView text(String s,int size,int color,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(color);if(bold)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);v.setLineSpacing(0,1.15f);return v;}
    private TextView center(String s,int size,int color,boolean bold){TextView v=text(s,size,color,bold);v.setGravity(Gravity.CENTER);return v;}
    private LinearLayout column(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}
    private GradientDrawable bg(int fill,int stroke,int radius,int width){GradientDrawable d=new GradientDrawable();d.setColor(fill);d.setCornerRadius(dp(radius));if(width>0)d.setStroke(dp(width),stroke);return d;}
    private View space(int h){View v=new View(this);v.setLayoutParams(new LinearLayout.LayoutParams(1,dp(h)));return v;}
    private LinearLayout.LayoutParams weight(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-2,1);p.setMargins(dp(3),0,dp(3),0);return p;}
    private String firstName(String full){String[] p=full.trim().split("\\s+");return p.length>0?p[0]:full;}
    private String bureaus(JSONArray a){if(a==null)return "—";StringBuilder s=new StringBuilder();for(int i=0;i<a.length();i++){if(i>0)s.append(" · ");s.append(a.optString(i));}return s.toString();}
    private String date(String iso){if(iso==null||iso.isEmpty()||iso.equals("null"))return "Pendiente";try{String raw=iso.length()>=10?iso.substring(0,10):iso;Date d=new SimpleDateFormat("yyyy-MM-dd",Locale.US).parse(raw);return new SimpleDateFormat("d 'de' MMMM 'de' yyyy",new Locale("es","MX")).format(d);}catch(Exception e){return iso;}}
    private String stage(String s){if("stabilization".equals(s))return "Etapa de estabilización";if("rebuilding".equals(s))return "Etapa de reconstrucción";if("growth".equals(s))return "Etapa de crecimiento";return "Progreso financiero";}
    private String status(String s){if("complete".equals(s))return "COMPLETA";if("processing".equals(s))return "PROCESANDO";return s.toUpperCase(Locale.ROOT);}
    private String priority(String s){if("high".equals(s))return "PRIORIDAD ALTA";if("medium".equals(s))return "PRIORIDAD MEDIA";return "PRIORIDAD BAJA";}
    private int priorityColor(String s){if("high".equals(s))return Color.rgb(190,65,65);if("medium".equals(s))return Color.rgb(202,132,32);return teal;}
    private String fileIcon(String mime){if(mime.contains("pdf"))return "PDF";if(mime.contains("image"))return "IMG";if(mime.contains("word"))return "DOC";return "FILE";}
    private String fileSize(long b){if(b<1024)return b+" B";if(b<1048576)return (b/1024)+" KB";return String.format(Locale.US,"%.1f MB",b/1048576.0);}
    private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
}
